tab<-read.table(file="C:\\Users\\pc\\Downloads\\Absenteeism_at_work.csv", header = TRUE, sep=";")
head(tab)
resp_dis = tab[tab$Reason.for.absence == 10, ]
head(resp_dis)
myhist=hist(resp_dis$Age, col = 'red')
library(nortest)
shapiro.test(resp_dis$Age)
ad.test(resp_dis$Age)
cvm.test(resp_dis$Age)
lillie.test(resp_dis$Age)
sf.test(resp_dis$Age)
cir_dis = tab[tab$Reason.for.absence == 26, ]
head(cir_dis)
myhist=hist(cir_dis$Age, col = 'red')
shapiro.test(cir_dis$Age)
sf.test(cir_dis$Age)
ad.test(cir_dis$Age)
cvm.test(cir_dis$Age)
lillie.test(cir_dis$Age)
library(car)
y <- c(cir_dis$Age, resp_dis$Age)
group <- as.factor(c(rep(1, length(cir_dis$Age)), rep(2, length(resp_dis$Age))))
var(cir_dis$Age)
var(resp_dis$Age)
leveneTest(y, group)
leveneTest(y, group, center = mean)
bartlett.test(y, group)
fligner.test(y, group)
library(ISwR)
var.test(resp_dis$Age, cir_dis$Age)