tab<-read.table(file="C:\\Users\\market4\\Downloads\\adult.data", header = TRUE, sep=",")
head(tab)
summary(tab)

Workclass<-as.factor(tab$workclass)
tab<-cbind(tab, Workclass)
Occupation<-as.factor(tab$occupation)
tab<-cbind(tab, Occupation)
Education<-as.factor(tab$education)
tab<-cbind(tab, Education)
Sex<-as.factor(tab$sex)
tab<-cbind(tab, Sex)
Native_country<-as.factor(tab$native.country)
tab<-cbind(tab, Native_country)
Income<-as.factor(tab$income)
tab<-cbind(tab, Income)
tab<-tab[, -c(2,4,6,7,8,9,10,14,15)]
summary(tab$Education)
summary(tab[4:5])
mean(tab$hours.per.week)
median(tab$hours.per.week)
quantile(tab$hours.per.week, c(0.25, 0.5, 0.75))
var(tab$age)
sd(tab$age)
sd(tab$age)/mean(tab$age)
library(psych)
describe(tab$age)
id<-c(seq(1,32561, by = 1))
plot(id, tab$age,type = "l")
hist(tab$age)
describeBy( tab$age, group = tab$Income)